### ISSUE TITLE
desugar the composition DSL

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#114]
Currently, we provide a mechanism that allows to express `Type` structure via class properties or fields syntax. For example,

```js
class Person {
  name = String;
  age = Number;
  pastResidences = [Address]
}
```

When we create a microstate with `Microstate.create(Person)`, we built a tree from this Type. In the process, we call `desugar` to convert the provided Type into a Type that microstates can use to build state and transitions. 

After the tree is created, we call flatMap on the tree and lazily invoke `initialize` transition to allow each type that describes an initialize transition an opportunity to convert the microstate's value into value that it needs to setup that microstate. 

The construction of the tree is currently someone implicit. We could make it more explicit by treating our composed Type declaration as sugar for longer syntax. The above example would be equivalent to,

```js
class Person {
  name = Microstate.create(String)
  age = Microstate.create(Number)
  pastResidences = Microstate.create([Address])
}
```

When microstates creates a Tree, it would convert the sugar Type declaration into the long form Microstate declaration. We would use this tree from this created Microstate when building the initial tree. 

This could make it easy for us to specify default values for #50 by doing this,

```js
class Person {
  name = Microstate.create(String, 'John Doe')
  age = Microstate.create(Number, 18)
  pastResidences = Microstate.create([Address])
}
```

We could further extend the sugar syntax by allowing to express default value with `new Type(value)` syntax. For example,

```js
class Person {
  name = new String('John Doe') // desugar to Microstate.create(String, 'John Doe')
  age = new Number(18); // desugar to Microstate.create(Number, 18)
  pastResidences = [Address]
}
```

We can make it easier to consume Microstates in TypeScript environment using this long from syntax.

**Comment by cowboyd** [comment]
The entire picostates architecture is based on this premise.
