### ISSUE TITLE
Release fully packaged umd to npm

### ISSUE THREAD

**Issue by knownasilya** [microstates/microstates.js#134]
For https://github.com/cowboyd/ember-microstates/pull/69

Even as a 'beta' release would be fine because right now it's not possible to test that PR in your app without building manually.

**Comment by taras** [comment]
I did it, but I messed up the version name (sorry) 

Try microstates@0.7.4-bata.1

**Comment by knownasilya** [comment]
Works great

**Comment by cowboyd** [comment]
Looks like this issue has been resolved.
