### ISSUE TITLE
Normalization Idea

### ISSUE THREAD

**Issue by zhDmitry** [microstates/microstates.js#151]
there is library https://github.com/mfpiccolo/blue-chip which does normalization and it uses classes approach either. So maybe there is a way to make integration for it to have some store normalisation like you wrote in "future" section.

**Comment by mfpiccolo** [comment]
I am going to be writing the state management layer in blue-chip as adapters so potentially microstates could be used as an adapter to integrate.  `blue-chip-microstates`

**Comment by taras** [comment]
@zhDmitry thank you for pointing us to blue-chip. I was not aware of this library. It looks great.

@mfpiccolo one of the challenges of building `adapters` with Microstates is that Microstates doesn't currently have a way to compose in Microstates that have side effects. We're looking at how this could be done. We generally want to maintain the same APIs but allow Microstates to automatically handle async operations.

For example, it could look like this

```js
class Adapter {
  async findOne() {
    return fetch(this.findOneUrl);
  }
}

class MyApp {
  products = Adapter.of(Product)
}
```

To use it, you would do this,

```js
let myapp = create(MyApp);

myapp.products.findOne()
// promise
```

Microstates would take care of merging the result of the async operation into the correct place in the data structure while other operations might have happened as well. We're thinking about what we can borrow from `ember-concurrency` to manage asynchrony inside of async microstates. This is on the horizon as soon as Microstates state machine primitive stabilizes.
