### ISSUE TITLE
Logo proposal for Microstates

### ISSUE THREAD

**Issue by joshuacarlito** [microstates/microstates.js#155]
Hi sir :) I have observed that microstate has no logo yet and lately I have been contributing on open source projects. I am a graphics designer and if you want a logo sir, I can make a logo for you or you can suggest anything about the logo and I will digitalize it. Thank you sir ! Have a nice day !!1

**Comment by taras** [comment]
HI @joshuacarlito thank you for reaching out. We didn't do a detailed logo because we didn't have the right designer. Maybe you're this person :) We were hoping to create a logo that looks like a coat of arms. Can you do illustration as well? Is it possible to see examples of your style?

**Comment by joshuacarlito** [comment]
Oh, yeah I think I'm the one:) I'm confused with " coat of arms" sir so I searched on google. Does coat of arms looks like this?
![image](https://user-images.githubusercontent.com/41003000/42630011-f52e8a5c-8607-11e8-8397-159b4574dfb3.png)

**Comment by taras** [comment]
Here is what we used as a reference 
![1200px-flag_of_san_marino svg](https://user-images.githubusercontent.com/74687/42631411-23deaa04-85a8-11e8-9cb6-949eac67c7bb.png)

**Comment by joshuacarlito** [comment]
Sorry for having late replies, been busy lately. So you like a logo similar to coat of arms sir, right? What do you want to be in the coat of arms? (symbols, signs, or cliplarts) any suggesttions?

**Comment by joshuacarlito** [comment]
This is a microstates initials logo, M and S, wherein the S is rotated...
![microstates3](https://user-images.githubusercontent.com/41003000/42722883-7c926bba-8786-11e8-8f17-cc6dc35afb48.png)

**Comment by taras** [comment]
Hi @joshuacarlito, thank you for taking the time to make the logos. They look great but they're not really what we're looking for. 

Microstates is quiet different than other state management tools because it creates a foundation that can be used to create shared solutions. One of our goals is to foster a community where people will share solutions to state problems. Sharing of solutions works best in smaller communities. So we want to foster many small communities around the world who use Microstates. 

I would like for our logo to be a basis for localized logos. [Ember.js Mascot](https://emberjs.com/mascots/) is a great example of this. Ideally, our logo would be a coat of arms that would be standard as a base, but inside the coat of arms we can make city specific artwork.

It's quiet possible that this is not in your wheelhouse but that's what we have in mind.

**Comment by joshuacarlito** [comment]
Thank you for your feedback @taras .This is my design @taras. I kept in simple and clean.
 ![rect4046](https://user-images.githubusercontent.com/41003000/43032516-32c2ccea-8ceb-11e8-9e29-298a62d0ceaa.png)

**Comment by taras** [comment]
@joshuacarlito this is actually pretty great. We just need to figure out imagery should go onto the shield and the crown. This is really great. Thank you :)

**Comment by joshuacarlito** [comment]
So what changes do you want sir?

**Comment by taras** [comment]
@joshuacarlito I'm not sure :( I need to figure out what imagery to use. Here is what I described to a friend when I was talking to him about logo for microstates.

1. building blocks - microstates are designed to plugin in together, some imaginery that represents making things from small things. 
2. a tree - a microstate is a wrapper around a tree which does all of the hard parts of microstates
3. standing on shoulders of giants - community creating sharable microstates that others can use
4. elevation - bringing people out of the swamp of managing state into higher ground

What do you think?

**Comment by ematipico** [comment]
A tree made of bricks? :smile:

**Comment by cowboyd** [comment]
I also wonder if the primitive types could be represented on the coat of arms: 'boolean', 'number', 'string'

**Comment by SamKeathley** [comment]
@cowboyd also said a state machine could be a cool possibility for within the coat of arms. This was said in the office; putting it here so we don't forget that rad idea.

**Comment by taras** [comment]
Yeah, a cool state machine in the coat of arms would be great

**Comment by cowboyd** [comment]
We have an interim logo for now, so closing until/when we want to re-open discussion.
