### ISSUE TITLE
Transitions from inside inherited transition methods

### ISSUE THREAD

**Issue by TeknoFiend** [microstates/microstates.js#208]
Really liking this project and started playing with building some adapters for AJAX for use in our product.  Ran into a little issue but maybe I'm just too far out of bounds.

If I define a transition method in a superclass (`doubleTransition` below) and the Microstate object is nested (`Person` instance nested under a `ContainerState` instance below).  Then the encompassed transitions (the `set`s inside `doubleTransition`) don't seem to return the correct the thing (they return a new top-level state instead of the state at `this`s level.  Notice the commented out `doubleTransition` defined directly in `Person` that works as expected.

```
class Model {
  doubleTransition() {
    let newState = this.age.set(53);    // `newState` set to a `ContainerState` Microstate
    return newState.name.set("Weston"); // So this doesn't work (`name` is on `Person`)
  }
}

class Person extends Model {
  age = Number
  name = String

  // Works as expected when defined here
  // doubleTransition() {
  //   let newState = this.age.set(53);    // `newState` set to a `Person` Microstate
  //   return newState.name.set("Weston"); // So this does what's expected and the transitions "chain"
  // }
}

class ContainerState {
  person = Person
}

let state1 = create( ContainerState, { person: { age: 10, name: "Homer" } } );
let state2 = state1.person.doubleTransition();
console.log( state1.state );
console.log( state2.state );
```

I tried looking through the source but it's a bit beyond my current aptitude 😅 

Maybe because we're using Babel and not native `class`es, wondering if others see the same behavior.  I noticed that I can't define custom transitions as class properties, maybe that's related:

```
class Person {
  getOlder = () => {  this.age.set(99); }  // age.set is not a function
}
```

Sorry for the gripes, really am liking using Microstates so far!

**Comment by cowboyd** [comment]
No worries about gripes, these are important to flesh out!

1) Transitions from inside inherited transition methods

This is definitely a bug and needs to be fixed.

2) This is actually not doing what you think it will be doing :)

```js
class Person {
  getOlder = () => {  this.age.set(99); }  // age.set is not a function
}
```

Microstates treats all instance properties as sub-states. In this case, microstates will treat `getOlder` as a substate whose Type is `() => {  this.age.set(99); }`. There are two reasons that it's like this. The first is that it's very hard to robustly discriminate between a constructor like `Number` or `Object` or `MyClass` and an normal JavaScript function. The second is that there needs to be some level of analysis of transitions without actually instantiating the object and that means that they all need to live on the prototype.

It's an interesting and perfectly valid intuition, and I'm wondering how we can message that to keep folks from bumping up against that wall. Maybe complaining if the function doesn't have a name?

Notice how in this example:

```
❯❯❯❯ yarn start                                                                  ~/C/microstates.js master
yarn run v1.7.0
$ node repl.js
> class HighFive { highFive = () => 5 }
'use strict'
> create(HighFive, 3)
Microstate<HighFive> { highFive: Microstate<> { state: undefined }, state: 3 }
```

See how the `highFive` property is actually a microstate with an anonymous type `Microstate<>`?

Maybe just disallow that? I dunno.

**Comment by cowboyd** [comment]
It's still a bug, but I do have one observation. It seems a little counter to the idea of strict Liskov substitution. 

```js
class Model {
  doubleTransition() {
    let newState = this.age.set(53);   
    return newState.name.set("Weston"); 
  }
}
```

In other words the superclass transition depends on properties that are not guaranteed to be present.

One potential workaround, which might even end up working out for the better is instead of using inheritance, use a factory for containment:

```
function Record(Type) {
  return class Record {
    isLoaded = Boolean;
    isInFlight = Boolean;
    content = Type;

    load(data) {
      return this
        .content.set(data)
        .isInFlight.set(false)
        .isLoaded.set(true);
    }
  }
}

class Person {
  name = String;
  age = Number;
}

let person = create(Record(Person));

fetch(`people/${id}`).then(data => person = person.load(data));

```

**Comment by TeknoFiend** [comment]
Thanks for the thorough response!

Yes, I see the difficulty with the instance properties now.  Thanks for the explainer.

Yes, I like the idea of the factory!  I think it will actually help with 1 or 2 rough edges I have.

**Comment by taras** [comment]
@TeknoFiend does Charles' answer address your question? Do you still want this open or should I close it?
