### ISSUE TITLE
Elements of `Array` lose their microstate attributes

### ISSUE THREAD

**Issue by TeknoFiend** [microstates/microstates.js#210]
I'm not sure if this is a bug or expected behavior but when using `Array` or `Object` and `push`ing or `put`ing values in, only the last value has its microstate attributes, the rest only hold on to the bare `state` attribute.  Easier to show I think:

```
class Foo {
  name = String
}

let state = create( Array ); // Changing this to `create( [Foo] )` works

let state2 = state.push( create( Foo, { name: "Anna" } ) );
console.log( state2[0] ); // => Microstate {name: Microstate, state: {…}, Symbol(Meta): Meta}

let state3 = state2.push( create( Foo, { name: "Weston" } ) );
console.log( state3[0] ); // => Microstate {state: {…}, Symbol(Meta): Meta}
console.log( state3[1] ); // => Microstate {name: Microstate, state: {…}, Symbol(Meta): Meta}
```

Notice that `state3[0]` is missing `name` (though `name` does appear with the proper value inside `state`).

As I mentioned in the code, using the typed array notation (eg `[Foo]`) works.  Maybe this works as-expected b/c of the missing type information but I was hoping to use `Array` (actually `Object`) as a polymorphic store.

I've since worked around this difficulty so this isn't in my way but I thought you all would like to know in case it _is_ a bug.

**Comment by cowboyd** [comment]
This is timely since I'm currently [refactoring the way `Array` works (and eventually `Object` too)](https://github.com/microstates/microstates.js/pull/209).

I'd say it's not so much a bug as "currently undefined behavior". Right now, what's happening is that we're closing the array type over the bare array state each time: https://github.com/microstates/microstates.js/blob/master/src/types/array.js#L14-L16 And so it will try to recast each value as being of the array parameter on every transition.

I think that it would be a helluva lot less useful if it didn't act as though you describe though, so I'm going to see if we can't land it.

**Comment by cowboyd** [comment]
Don't know how you're working around it, but one way would be to use "self-healing" polymorphism by using a type tag and an initializer.

```js
class Vehicle {
  initialize(data) {
    let { type } = data;
    switch (type) {
    case 'car':
      return create(Car, data);
    case 'motorcycle':
      return create(Motorcycle, data);
    }
  }
}

class Car extends Vehicle {
  wheels = 4;
}

class Motorcycle extends Vehicle {
  wheels = 2;
}

create([Vehicle])
  .push({type: 'car'})
  .push({type: 'motorcycle'})
  .push({type: 'car'})
```

**Comment by TeknoFiend** [comment]
FWIW - I worked around it by dynamically constructing the Type shape:

```
function ResourceStore() {
  resourceTypes.forEach( klass => {
    this[klass.name] = ResourceTypeGenerator(klass);
  });
}

let microstate = create( ResourceStore );

resourceType.models.forEach( klass => {
  let resource = create(ResourceTypeGenerator(klass));
  microstate = microstate[klass.name].set( resource );
});
```

Which is a bit more precise (and has other benefits I think) than using a plain `Object` for the root microstate.

**Comment by TeknoFiend** [comment]
Thanks for the consideration and the suggestion.

**Comment by cowboyd** [comment]
☝️ that is actually really cool, and I think we need to include it into a cookbook of some kind.

I've been thinking about this feature, and I'm having trouble reconciling it with another stated goal of microstates which is for the state to be serializable and deterministic. I other words, if I say:

```
class Thing {}
class Other extends Thing;
let microstate1 = create([Thing], [{thing: 'one'}, {thing: 'two'});
let microstate2 = micro.push(create(Other, {other: 'thing'}));

//microstate2 should be equivalent to create([Thing], microstate2.state)
```

And so persisting the runtime type of the thing between transistions means that there is some information about the data that is no longer contained solely by the state, which means it is not 100% deterministically serializable, which complicates time-travel debugging, snapshoting, hot reloading.

Would it make more sense to actually ignore the runtime type from the get-go?

**Comment by rkeeler** [comment]
@cowboyd Would we lose anything that tracking the runtime type currently enables? I agree that deterministic serialization is an important goal. I also think that if inheritance is going to be a suggested or supported pattern to use with microstates, then it's important that types never get coerced into their base classes. In my mind, ideally collection microstates would just let their items remain whatever types they happen to be and never have their typed coerced behind the scenes. This makes me wonder if it should even matter that the items actually be subclasses of the type the microstate array was declared with. As long each item in the array has the necessary properties and transition names defined, is there a reason microstates needs to know about the actual inheritance hierarchy or type of the object?

This would make serialization repeatable and consistent. Although deserializing back into the correct microstate types is still a challenge. 

What do you think about adopting the pattern ImmutableJS and json.net for C# use where you can optionally supply a deserialization/reviver function?

```js
class Animal {
  species: String;
}

class Pet extends Animal {
  name: String;
}

let rawAnimals = [
  { species: 'lion' },
  { species: 'dog', name: 'Toto' }
];

function deserializer(obj) {
  if (obj.name) {
    return create(Pet, obj);
  } else {
    return create(Animal, obj);
  }
}

let animals = create([Animal], rawAnimals, deserializer);
```

**Comment by cowboyd** [comment]
> I guess this also makes me wonder if there is any real need to declare what type the array (or other collection type) holds, other than as a hint to the developer about what might be in the array microstate.

Declaring the type of the array lets you do this:

```js
let array = create([Automobile]).push({make: 'Ford', model: 'T-Bird'});
```

without having to explicitly create every object.

One alterative is that we could have some sort of implicit support for tagged sum types a-la fantasy land https://github.com/fantasyland/daggy

Not saying that we should use the same syntax, but have support for union types that have a tag implicit to the way they are serialized might be worthwhile.

**Comment by cowboyd** [comment]
It sounds like all of these are some version of the pattern where you have a "standin" type that in its initialize transition transition to the "real" type. What if we had a union type constructor like the haskell

```haskell
data Mabye a= Just a | Nothing
```
equivalent would be:

```js
const Maybe = Union(T => ({
  just: class Just {
    content = T;
  },
  nothing: class Nothing {}
});
```

Which would generate  a class like:

```
class Maybe {
  initialize(value) {
    switch(value.type) {
    case 'just':
      return create(Just, value);
    case 'nothing':
      return create(Nothing, value);
    default:
      // not sure what happens here
  }
}
```

**Comment by cowboyd** [comment]
I'm going to mark this as closed, since with the tree being lazy, and also serializable, the only time type-shifting is allowed is inside the `initialize` method. We'll use this capability for Union types and other higher order microstates, but for the time being, the type of a microstate must be a pure function of its value.
