### ISSUE TITLE
Map for Object Microstates

### ISSUE THREAD

**Issue by rkeeler** [microstates/microstates.js#224]
Do you have any plans to add a `map` transition to Object microstates? I have a collection of values that i want to store in an object keyed by ids so I get O(1) value lookup. However, microstates doesn't seem to currently support functor operations on Objects. I can work around it with a forEach loop, and it's not like the difference of 1 line of code vs 5 is a huge deal. However, microstate code is highly functional in style already, so it would be nice if this was supported too.

<details>
<summary>
Example Code (https://codesandbox.io/s/vv709w87v5)
</summary>

```js
class Todo {
  id = create(String);
  completed = create(Boolean, false);
}

class MyModel {
  todosById = create({ Todo });

  completeAll() {
    let newValue = this;

    // I wish there was a functional way to do this
    // e.g. this.todosById.map(todo => todo.completed.set(true));

    Object.keys(this.todosById.state).forEach(id => {
      newValue = newValue.todosById[id].completed.set(true);
    });

    return newValue;
  }
}
```
</details>

P.S. I tried making a PR to add it myself, but due to my inexperience with functional lenses I couldn't quite make it work. I tried something like the following, but then I end up with each item in the dictionary belonging to it's own world due to the way lenses return the context object. 

```js
// src/types/object.js
  map(fn) {
    return map((value, key) => fn(this[key], key), this.state);
  }
```

I wanted to map over `this` rather than `this.state`, but when I did that I ended up mapping over extra keys like 'state' that aren't actually part of my user land object.

**Comment by taras** [comment]
@rkeeler we should probably support `map, reduce, filter` transitions for the object. Did you look at how Array implements map? 

I believe your implementation is very close, it's just missing reference to the contextualized microstate. 

```js
map(fn) {
    return this.state.map((item, index) => fn(Meta.source(this[index])));
  }
```

I believe you just need `fn(Meta.source(this[key], key)`. 

Check if this works.

**Comment by rkeeler** [comment]
Ah, yes that's what it was. Thanks @taras  I'll submit a PR soon. I want to clean up the test I wrote and I might go ahead and add `reduce` and `filter` as well.
