### ISSUE TITLE
Extending NumberType looses NumberType's behaviour

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#269]
```js
const { create, NumberType } = require('microstates');

create(NumberType).state
//> 0

create(class extends NumberType {}).state
//> undefined
```

`.state` should be 0

**Comment by cowboyd** [comment]
I'm still not convinced that inheritance is something we want to commit to supporting, at least with respect to initializers. The problem here is that the initializer isn't being invoked, and this is actually kinda necessary to support union types. 

```js
create(class extends NumberType {
  initialize(...args) { 
    return this.super(...args);
  }
}).state
```

Should work.

**Comment by taras** [comment]
It will be very surprising for people if inheritance works sometimes and not others. 

Initialization still feels very uncertain for me. Can we simplify things if we made initializer static again? It would addrsss this problem and probably simplify initialize behaviour.

**Comment by cowboyd** [comment]
Yeah, I'm definitely open to re-thinking how this happens.

**Comment by taras** [comment]
Not a bug.

**Comment by mharris717** [comment]
+1 for it being confusing. That doesn't mean it's right or wrong, but `initialize` on the superclass not being used confused me for a good bit.

**Comment by taras** [comment]
I agree that we need to revisit this.

**Comment by cowboyd** [comment]
Some options to consider:

- Walk the chain up to to the _nearest_ `initialize()` method?
- maybe use `constructor()` now that we don't depend on jumping through hoops inside the the `ObjectType` constructor anymore?
