### ISSUE TITLE
the 'map' query doesn't work with object microstates

### ISSUE THREAD

**Issue by rkeeler** [microstates/microstates.js#271]
Hey guys. I'm not sure if it's supposed to be supported since there aren't docs for queries yet (not a complaint. I know there's another issue for adding them to the docs), but the `map` query isn't working with Object microstates. I think it makes sense that you should be able to map over the key/value pairs in the object, so I think this is probably a bug. Here's a link demonstrating the issue. 

https://runkit.com/rkeeler/microstates-map-query-bug

**Comment by taras** [comment]
It should be supported, we just didn't implement it. It's missing the [Symbol.Iterator implementation that Array has](https://github.com/microstates/microstates.js/blob/master/src/types/array.js#L83).

@cowboyd what does this do? https://github.com/microstates/microstates.js/blob/master/src/types/array.js#L99

**Comment by cowboyd** [comment]
Microstate queries work against any JavaScript Iterable at all. All you need to do is implement `Symbol.iterator` for object and it will work.

```js
*[Symbol.iterator]() {
   for (let key of Object.keys(this)) {
    yield this[key];
   } 
}
```

Course, we don't have generators supported, so would have to unroll that into a manual iterator.

```js
[Symbol.iterator]() {
  let object = this;
  let iterator = Object.keys(this)[Symbol.iterator];
  return {
    next() {
      let next = iterator.next();
      return {
        get done() { return next.done; }
        get value() { return object[next.value]; }
    }
  }
}
```

**Comment by cowboyd** [comment]
> I think it makes sense that you should be able to map over the key/value pairs in the object, so I think this is probably a bug

Ah yeah, probably a better idea to have the iteration yield sets of key/value pairs.

**Comment by cowboyd** [comment]
>@cowboyd what does this do? >https://github.com/microstates/microstates.js/blob/master/src/types/array.js#L99

It's a static initializer for a parameterized class, so that you can declare any typeclasses that it implements.... in this case `Profunctor`

https://github.com/microstates/microstates.js/blob/master/src/parameterized.js#L7-L9

**Comment by taras** [comment]
@rkeeler will you be able to put together a PR for this? We need it for `@microstates/ember` because without it `{{each-in}}` doesn't work.

**Comment by taras** [comment]
I'm actually going to add this now.

**Comment by rkeeler** [comment]
Okay. Yeah, I hadn't a chance to start working on a PR yet. But i will definitely test it out once you are done.

**Comment by taras** [comment]
I believe this is done now. Let's reopen if not the case.
