### ISSUE TITLE
Should ArrayType type have a `remove` transition?

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#274]
Lists in `ember-microstates` have `remove` operation that allows to remove an item from the list. In React, it's easy to use ArrayType#filter, but in Ember Templates it's difficult to define ad-hoc functions. Should we add a `remove` transition? It could be as simple as just calling filter.

```js
remove(item) {
  return this.filter(s => valueOf(s) === valueOf(item));
}
```

What do you think?

**Comment by cowboyd** [comment]
I think this addition is long overdue. The only question is if there's any prior art about what we should call it: `remove` or `delete`

**Comment by taras** [comment]
‘delete’ so it’ll be consistent with object type?

**Comment by taras** [comment]
Actually, on second thought. `delete` is remove by index. `remove` is remove by value.
