### ISSUE TITLE
Publishing to NPM with branch as tag

### ISSUE THREAD

**Issue by minkimcello** [microstates/microstates.js#375]
![Screen Shot 2019-10-08 at 11 07 08 AM](https://user-images.githubusercontent.com/29791650/66408054-3db66d80-e9bc-11e9-8337-2d4fe11708ac.png)

Since `actions/npm` has been deprecated, I was reviewing how we should update our workflow to use `actions/setup-node` and how we can incorporate the use of npm tag.

Publishing the preview with the branch as its tag is as simple as `run: npm publish --tag $GITHUB_HEAD_REF`.

However, removing the tag after the pull request is closed has its issues. Checkout fails on workflows that are run on pull requests after they are closed because that ref is lost so we still have access to `GITHUB_HEAD_REF` but can't retrieve package name from `package.json`.

We can't run this on the base repository because: 1. we don't have any context on the pull request that the commit was generated from so there are no ways of retrieving the branch name of head; 2. tags of previews from pull requests that are closed but not merged are overlooked.

Possible solution: If it's safe to assume the repository name will be the same as the npm package name, we can use `GITHUB_REPOSITORY`. However this will not work on scoped packages or forked repositories (none of the workflows are meant to run on forked repositories anyway).

I've tested this on [minkimcello/georgia](https://github.com/minkimcello/georgia/tree/features-2) and can confirm it works fine.

**Comment by cowboyd** [comment]
What if we just remove *all* stale tags on NPM with every push to a protected branch?

In other words, we pull down the npm tags (apart from `latest`) and if there is no corresponding branch in the repository, then we delete it.

**Comment by cowboyd** [comment]
> If it's safe to assume the repository name will be the same as the npm package name, we can use GITHUB_REPOSITORY. However this will not work on scoped packages or forked repositories (none of the workflows are meant to run on forked repositories anyway).

Unfortunately, this is not a safe assumption. It will be unlikely with scoped packages like `@bigtest/convergence` and downright impossible with multi-package repos.

I think we're ok though, because if we use the solution above and just prune tags according to what we see in the repository, then it's totally sufficient to just checkout the current `GITHUB_SHA`. 

Another avenue to explore would be the [`delete`][1] event which is triggered whenever a branch is deleted.

[1]: https://developer.github.com/v3/activity/events/types/#deleteevent

**Comment by minkimcello** [comment]
> we pull down the npm tags (apart from latest) and if there is no corresponding branch in the repository, then we delete it.
that means any `dev` or `beta` tags will go too unless we specify otherwise. is there any scenario where we (or some other team that comes across our action) might have npm tags that might not correspond to branches? If so it would be nice because we can fit the "cleanup" in the release workflow.

> If we use the solution above and just prune tags according to what we see in the repository, then it's totally sufficient to just checkout the current GITHUB_SHA.

What you're saying is we can just checkout `GITHUB_SHA` (or `GITHUB_HEAD_REF`) and fetch the package name from there instead?

> Another avenue to explore would be the delete event which is triggered whenever a branch is deleted.

This might be a good solution. I'll have a look at this.

**Comment by minkimcello** [comment]
Solution proposed [here](https://github.com/microstates/microstates.js/pull/378)
