### ISSUE TITLE
Update logo for social preview

### ISSUE THREAD

**Issue by cowboyd** [microstates/microstates.js#398]
We have a logo for microstates, we should use it in the social preview settings found at https://github.com/microstates/microstates.js/settings

**Comment by minkimcello** [comment]
![Screen Shot 2020-04-21 at 12 54 22 PM](https://user-images.githubusercontent.com/29791650/79891724-67bb0480-83cf-11ea-966a-08f3a71599e1.png)
![Screen Shot 2020-04-21 at 12 55 00 PM](https://user-images.githubusercontent.com/29791650/79891726-68539b00-83cf-11ea-9686-9621ca699087.png)

**Comment by cowboyd** [comment]
😍 😍 😍
