### ISSUE TITLE
default value of a composed simple state

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#50]
If you define a microstate like 

```js
class Products {
  filter = MS.String;
}
```

It would be helpful to be able to specify a default value for the `filter` when one is not specified. This not currently possible.

**Comment by cowboyd** [comment]
perhaps:

```js
class Products {
  filter = MS.String('abc');
}
```

**Comment by taras** [comment]
That would be nice ^^

**Comment by taras** [comment]
If we move to native classes, then we could do `String('abc')`.

**Comment by taras** [comment]
Default values only make sense when defining a composed type. Composed types have `static create` method which can be used to specify default values for composed states.

For the above example, to specify a default value for `filter` we can do the following,

```js
class Products {
  filter = String();
  static create(attrs) {
    let { 
     filter = 'abc'
    } = attrs;

    return create(Products, { filter });
  }
}
```

Do we need another mechanism to provide default values other than the existing `static create` method?

**Comment by cowboyd** [comment]
Or, if we do away with "constants" we just say:

```javascript
class Products {
  filter = 'abc';
}
```

**Comment by cowboyd** [comment]
alternatively:

```js
class Products {
  @default('abc')
  filter = String;
}
```

**Comment by taras** [comment]
@cowboyd I'm good with eliminating constants if this helps us. We can always introduce `@readonly` or `@constant` which will do the same thing as constants.

**Comment by cowboyd** [comment]
The picostates way to provide is a default is:

```js
class Products {
  filter = create(String, 'abc');
}
```
