### ISSUE TITLE
Rename sum to add on Number

### ISSUE THREAD

**Issue by sivakumar-kailasam** [microstates/microstates.js#85]
`Sum` is the result of `addition` of two or more numbers, so to keep it inline with the `subtract` method, it'd probably be better to rename `sum` to `add` on the `Number` type.

**Comment by taras** [comment]
I'm going to create another issue with a summary of all transitions that are built into Microstates. I'd like to reduce the API down to the most essential. 

`addition` can be expressed as `increment(amount)`. So, think we should drop `sum` and `subtract` from Number type.

**Comment by sivakumar-kailasam** [comment]
Hopefully the table of contents on #84 covers all of them, unless there are more undocumented methods.

**Comment by taras** [comment]
Removed in #113
