### ISSUE TITLE
Provide an API to allow extending built in Types

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#88]
Our types should do a little as necessary but allow people to extend them if necessary. The changes that they introduce should be local to their implementation. One of the possibilities is to allow people to extend the built in Microstates class and override built in types. 

For example,

```js
class MyString extends StringType { 
}

class MyMicrostates extends Microstates {
   types = {
     String: MyString
   }
}
```

The above example would need to work with `static create` method.

**Comment by cowboyd** [comment]
I think if you want to have your own string, is it really that hard to just say

```js
class Foo {
  str = String;
}
```

?
